<?php

namespace Database\Seeders;

use App\Models\User;
use App\Models\Word;
// use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class DatabaseSeeder extends Seeder
{
    /**
     * Seed the application's database.
     */
    public function run(): void
    {
        // User::factory(10)->create();

        Word::insert([
            //53 kata benda mudah
            ['word' => 'berlari', 'type' => 'kerja', 'difficulty' => 'mudah'],
            // ['word' => 'indah', 'type' => 'sifat', 'difficulty' => 'mudah'],
            // ['word' => 'tetapi', 'type' => 'sambung', 'difficulty' => 'mudah'],

            //50 kata benda mudah
            ['word' => 'meja', 'type' => 'benda', 'difficulty' => 'mudah'],
            ['word' => 'kursi', 'type' => 'benda', 'difficulty' => 'mudah'],
            ['word' => 'buku', 'type' => 'benda', 'difficulty' => 'mudah'],
            ['word' => 'pensil', 'type' => 'benda', 'difficulty' => 'mudah'],
            ['word' => 'tas', 'type' => 'benda', 'difficulty' => 'mudah'],
            ['word' => 'sepatu', 'type' => 'benda', 'difficulty' => 'mudah'],
            ['word' => 'pintu', 'type' => 'benda', 'difficulty' => 'mudah'],
            ['word' => 'jendela', 'type' => 'benda', 'difficulty' => 'mudah'],
            ['word' => 'lantai', 'type' => 'benda', 'difficulty' => 'mudah'],
            ['word' => 'lampu', 'type' => 'benda', 'difficulty' => 'mudah'],

            ['word' => 'jam', 'type' => 'benda', 'difficulty' => 'mudah'],
            ['word' => 'kunci', 'type' => 'benda', 'difficulty' => 'mudah'],
            ['word' => 'rumah', 'type' => 'benda', 'difficulty' => 'mudah'],
            ['word' => 'mobil', 'type' => 'benda', 'difficulty' => 'mudah'],
            ['word' => 'motor', 'type' => 'benda', 'difficulty' => 'mudah'],
            ['word' => 'jalan', 'type' => 'benda', 'difficulty' => 'mudah'],
            ['word' => 'pohon', 'type' => 'benda', 'difficulty' => 'mudah'],
            ['word' => 'bunga', 'type' => 'benda', 'difficulty' => 'mudah'],
            ['word' => 'rumput', 'type' => 'benda', 'difficulty' => 'mudah'],
            ['word' => 'air', 'type' => 'benda', 'difficulty' => 'mudah'],

            ['word' => 'laut', 'type' => 'benda', 'difficulty' => 'mudah'],
            ['word' => 'sungai', 'type' => 'benda', 'difficulty' => 'mudah'],
            ['word' => 'gunung', 'type' => 'benda', 'difficulty' => 'mudah'],
            ['word' => 'langit', 'type' => 'benda', 'difficulty' => 'mudah'],
            ['word' => 'awan', 'type' => 'benda', 'difficulty' => 'mudah'],
            ['word' => 'matahari', 'type' => 'benda', 'difficulty' => 'mudah'],
            ['word' => 'bulan', 'type' => 'benda', 'difficulty' => 'mudah'],
            ['word' => 'bintang', 'type' => 'benda', 'difficulty' => 'mudah'],
            ['word' => 'batu', 'type' => 'benda', 'difficulty' => 'mudah'],
            ['word' => 'pasir', 'type' => 'benda', 'difficulty' => 'mudah'],

            ['word' => 'kaca', 'type' => 'benda', 'difficulty' => 'mudah'],
            ['word' => 'kertas', 'type' => 'benda', 'difficulty' => 'mudah'],
            ['word' => 'gelas', 'type' => 'benda', 'difficulty' => 'mudah'],
            ['word' => 'piring', 'type' => 'benda', 'difficulty' => 'mudah'],
            ['word' => 'sendok', 'type' => 'benda', 'difficulty' => 'mudah'],
            ['word' => 'garpu', 'type' => 'benda', 'difficulty' => 'mudah'],
            ['word' => 'roti', 'type' => 'benda', 'difficulty' => 'mudah'],
            ['word' => 'susu', 'type' => 'benda', 'difficulty' => 'mudah'],
            ['word' => 'bola', 'type' => 'benda', 'difficulty' => 'mudah'],
            ['word' => 'kado', 'type' => 'benda', 'difficulty' => 'mudah'],

            ['word' => 'bayi', 'type' => 'benda', 'difficulty' => 'mudah'],
            ['word' => 'anak', 'type' => 'benda', 'difficulty' => 'mudah'],
            ['word' => 'orang', 'type' => 'benda', 'difficulty' => 'mudah'],
            ['word' => 'ibu', 'type' => 'benda', 'difficulty' => 'mudah'],
            ['word' => 'ayah', 'type' => 'benda', 'difficulty' => 'mudah'],
            ['word' => 'kucing', 'type' => 'benda', 'difficulty' => 'mudah'],
            ['word' => 'anjing', 'type' => 'benda', 'difficulty' => 'mudah'],
            ['word' => 'burung', 'type' => 'benda', 'difficulty' => 'mudah'],
            ['word' => 'sapi', 'type' => 'benda', 'difficulty' => 'mudah'],
            ['word' => 'ayam', 'type' => 'benda', 'difficulty' => 'mudah'],

            //50 kata kerja mudah
            ['word' => 'makan', 'type' => 'kerja', 'difficulty' => 'mudah'],
            ['word' => 'minum', 'type' => 'kerja', 'difficulty' => 'mudah'],
            ['word' => 'tidur', 'type' => 'kerja', 'difficulty' => 'mudah'],
            ['word' => 'bangun', 'type' => 'kerja', 'difficulty' => 'mudah'],
            ['word' => 'lari', 'type' => 'kerja', 'difficulty' => 'mudah'],
            ['word' => 'lompat', 'type' => 'kerja', 'difficulty' => 'mudah'],
            ['word' => 'duduk', 'type' => 'kerja', 'difficulty' => 'mudah'],
            ['word' => 'berdiri', 'type' => 'kerja', 'difficulty' => 'mudah'],
            ['word' => 'berjalan', 'type' => 'kerja', 'difficulty' => 'mudah'],
            ['word' => 'baca', 'type' => 'kerja', 'difficulty' => 'mudah'],
            ['word' => 'tulis', 'type' => 'kerja', 'difficulty' => 'mudah'],
            ['word' => 'berbicara', 'type' => 'kerja', 'difficulty' => 'mudah'],
            ['word' => 'dengar', 'type' => 'kerja', 'difficulty' => 'mudah'],
            ['word' => 'lihat', 'type' => 'kerja', 'difficulty' => 'mudah'],
            ['word' => 'ambil', 'type' => 'kerja', 'difficulty' => 'mudah'],
            ['word' => 'taruh', 'type' => 'kerja', 'difficulty' => 'mudah'],
            ['word' => 'berpikir', 'type' => 'kerja', 'difficulty' => 'mudah'],
            ['word' => 'bermain', 'type' => 'kerja', 'difficulty' => 'mudah'],
            ['word' => 'menangis', 'type' => 'kerja', 'difficulty' => 'mudah'],
            ['word' => 'tertawa', 'type' => 'kerja', 'difficulty' => 'mudah'],
            ['word' => 'berenang', 'type' => 'kerja', 'difficulty' => 'mudah'],
            ['word' => 'melompat', 'type' => 'kerja', 'difficulty' => 'mudah'],
            ['word' => 'menyapu', 'type' => 'kerja', 'difficulty' => 'mudah'],
            ['word' => 'memasak', 'type' => 'kerja', 'difficulty' => 'mudah'],
            ['word' => 'membersihkan', 'type' => 'kerja', 'difficulty' => 'mudah'],
            ['word' => 'membuka', 'type' => 'kerja', 'difficulty' => 'mudah'],
            ['word' => 'menutup', 'type' => 'kerja', 'difficulty' => 'mudah'],
            ['word' => 'mencuci', 'type' => 'kerja', 'difficulty' => 'mudah'],
            ['word' => 'menggambar', 'type' => 'kerja', 'difficulty' => 'mudah'],
            ['word' => 'berbelanja', 'type' => 'kerja', 'difficulty' => 'mudah'],
            ['word' => 'membeli', 'type' => 'kerja', 'difficulty' => 'mudah'],
            ['word' => 'menjual', 'type' => 'kerja', 'difficulty' => 'mudah'],
            ['word' => 'belajar', 'type' => 'kerja', 'difficulty' => 'mudah'],
            ['word' => 'mengajar', 'type' => 'kerja', 'difficulty' => 'mudah'],
            ['word' => 'bertanya', 'type' => 'kerja', 'difficulty' => 'mudah'],
            ['word' => 'menjawab', 'type' => 'kerja', 'difficulty' => 'mudah'],
            ['word' => 'mengangkat', 'type' => 'kerja', 'difficulty' => 'mudah'],
            ['word' => 'menurunkan', 'type' => 'kerja', 'difficulty' => 'mudah'],
            ['word' => 'membawa', 'type' => 'kerja', 'difficulty' => 'mudah'],
            ['word' => 'memakai', 'type' => 'kerja', 'difficulty' => 'mudah'],
            ['word' => 'melepas', 'type' => 'kerja', 'difficulty' => 'mudah'],
            ['word' => 'mendaki', 'type' => 'kerja', 'difficulty' => 'mudah'],
            ['word' => 'turun', 'type' => 'kerja', 'difficulty' => 'mudah'],
            ['word' => 'mengemudi', 'type' => 'kerja', 'difficulty' => 'mudah'],
            ['word' => 'menonton', 'type' => 'kerja', 'difficulty' => 'mudah'],
            ['word' => 'menyanyi', 'type' => 'kerja', 'difficulty' => 'mudah'],
            ['word' => 'menari', 'type' => 'kerja', 'difficulty' => 'mudah'],
            ['word' => 'beristirahat', 'type' => 'kerja', 'difficulty' => 'mudah'],
            ['word' => 'memotong', 'type' => 'kerja', 'difficulty' => 'mudah'],
            ['word' => 'memeluk', 'type' => 'kerja', 'difficulty' => 'mudah'],

            //45 kata sambung mudah
            ['word' => 'dan', 'type' => 'sambung', 'difficulty' => 'mudah'],
            ['word' => 'atau', 'type' => 'sambung', 'difficulty' => 'mudah'],
            // ['word' => 'tetapi', 'type' => 'sambung', 'difficulty' => 'mudah'],
            ['word' => 'karena', 'type' => 'sambung', 'difficulty' => 'mudah'],
            ['word' => 'agar', 'type' => 'sambung', 'difficulty' => 'mudah'],
            ['word' => 'walaupun', 'type' => 'sambung', 'difficulty' => 'mudah'],
            ['word' => 'jika', 'type' => 'sambung', 'difficulty' => 'mudah'],
            // ['word' => 'sehingga', 'type' => 'sambung', 'difficulty' => 'mudah'],
            ['word' => 'supaya', 'type' => 'sambung', 'difficulty' => 'mudah'],
            ['word' => 'sampai', 'type' => 'sambung', 'difficulty' => 'mudah'],
            ['word' => 'meskipun', 'type' => 'sambung', 'difficulty' => 'mudah'],
            ['word' => 'sementara', 'type' => 'sambung', 'difficulty' => 'mudah'],
            ['word' => 'sebelum', 'type' => 'sambung', 'difficulty' => 'mudah'],
            ['word' => 'sesudah', 'type' => 'sambung', 'difficulty' => 'mudah'],
            ['word' => 'hingga', 'type' => 'sambung', 'difficulty' => 'mudah'],
            ['word' => 'namun', 'type' => 'sambung', 'difficulty' => 'mudah'],
            ['word' => 'lalu', 'type' => 'sambung', 'difficulty' => 'mudah'],
            ['word' => 'kemudian', 'type' => 'sambung', 'difficulty' => 'mudah'],
            ['word' => 'bahwa', 'type' => 'sambung', 'difficulty' => 'mudah'],
            ['word' => 'apalagi', 'type' => 'sambung', 'difficulty' => 'mudah'],
            ['word' => 'serta', 'type' => 'sambung', 'difficulty' => 'mudah'],
            ['word' => 'sedangkan', 'type' => 'sambung', 'difficulty' => 'mudah'],
            ['word' => 'melainkan', 'type' => 'sambung', 'difficulty' => 'mudah'],
            ['word' => 'berhubung', 'type' => 'sambung', 'difficulty' => 'mudah'],
            ['word' => 'bahkan', 'type' => 'sambung', 'difficulty' => 'mudah'],
            ['word' => 'dengan', 'type' => 'sambung', 'difficulty' => 'mudah'],
            ['word' => 'oleh', 'type' => 'sambung', 'difficulty' => 'mudah'],
            // ['word' => 'hingga', 'type' => 'sambung', 'difficulty' => 'mudah'],
            ['word' => 'sebab', 'type' => 'sambung', 'difficulty' => 'mudah'],
            ['word' => 'tentang', 'type' => 'sambung', 'difficulty' => 'mudah'],
            ['word' => 'dalam', 'type' => 'sambung', 'difficulty' => 'mudah'],
            ['word' => 'antara', 'type' => 'sambung', 'difficulty' => 'mudah'],
            ['word' => 'tetapi', 'type' => 'sambung', 'difficulty' => 'mudah'],
            ['word' => 'selain', 'type' => 'sambung', 'difficulty' => 'mudah'],
            ['word' => 'demi', 'type' => 'sambung', 'difficulty' => 'mudah'],
            ['word' => 'hanya', 'type' => 'sambung', 'difficulty' => 'mudah'],
            ['word' => 'malah', 'type' => 'sambung', 'difficulty' => 'mudah'],
            ['word' => 'padahal', 'type' => 'sambung', 'difficulty' => 'mudah'],
            ['word' => 'selama', 'type' => 'sambung', 'difficulty' => 'mudah'],
            ['word' => 'tanpa', 'type' => 'sambung', 'difficulty' => 'mudah'],
            ['word' => 'itu', 'type' => 'sambung', 'difficulty' => 'mudah'],
            ['word' => 'ini', 'type' => 'sambung', 'difficulty' => 'mudah'],
            // ['word' => 'kemudian', 'type' => 'sambung', 'difficulty' => 'mudah'],
            ['word' => 'terutama', 'type' => 'sambung', 'difficulty' => 'mudah'],
            ['word' => 'sehingga', 'type' => 'sambung', 'difficulty' => 'mudah'],
            // ['word' => 'sama sekali', 'type' => 'sambung', 'difficulty' => 'mudah'],
            // ['word' => 'setelah itu', 'type' => 'sambung', 'difficulty' => 'mudah'],
            ['word' => 'untuk', 'type' => 'sambung', 'difficulty' => 'mudah'],
            // ['word' => 'di mana', 'type' => 'sambung', 'difficulty' => 'mudah'],
            // ['word' => 'yang mana', 'type' => 'sambung', 'difficulty' => 'mudah'],

            ['word' => 'baik', 'type' => 'sifat', 'difficulty' => 'mudah'],
            ['word' => 'buruk', 'type' => 'sifat', 'difficulty' => 'mudah'],
            ['word' => 'besar', 'type' => 'sifat', 'difficulty' => 'mudah'],
            ['word' => 'kecil', 'type' => 'sifat', 'difficulty' => 'mudah'],
            ['word' => 'panjang', 'type' => 'sifat', 'difficulty' => 'mudah'],
            ['word' => 'pendek', 'type' => 'sifat', 'difficulty' => 'mudah'],
            ['word' => 'cepat', 'type' => 'sifat', 'difficulty' => 'mudah'],
            ['word' => 'lambat', 'type' => 'sifat', 'difficulty' => 'mudah'],
            ['word' => 'cantik', 'type' => 'sifat', 'difficulty' => 'mudah'],
            ['word' => 'tampan', 'type' => 'sifat', 'difficulty' => 'mudah'],
            ['word' => 'bagus', 'type' => 'sifat', 'difficulty' => 'mudah'],
            ['word' => 'jelek', 'type' => 'sifat', 'difficulty' => 'mudah'],
            ['word' => 'ringan', 'type' => 'sifat', 'difficulty' => 'mudah'],
            ['word' => 'berat', 'type' => 'sifat', 'difficulty' => 'mudah'],
            ['word' => 'mudah', 'type' => 'sifat', 'difficulty' => 'mudah'],
            ['word' => 'sulit', 'type' => 'sifat', 'difficulty' => 'mudah'],
            ['word' => 'senang', 'type' => 'sifat', 'difficulty' => 'mudah'],
            ['word' => 'sedih', 'type' => 'sifat', 'difficulty' => 'mudah'],
            ['word' => 'sejuk', 'type' => 'sifat', 'difficulty' => 'mudah'],
            ['word' => 'panas', 'type' => 'sifat', 'difficulty' => 'mudah'],
            ['word' => 'dingin', 'type' => 'sifat', 'difficulty' => 'mudah'],
            ['word' => 'lembut', 'type' => 'sifat', 'difficulty' => 'mudah'],
            ['word' => 'kasar', 'type' => 'sifat', 'difficulty' => 'mudah'],
            ['word' => 'bersih', 'type' => 'sifat', 'difficulty' => 'mudah'],
            ['word' => 'kotor', 'type' => 'sifat', 'difficulty' => 'mudah'],
            ['word' => 'terang', 'type' => 'sifat', 'difficulty' => 'mudah'],
            ['word' => 'gelap', 'type' => 'sifat', 'difficulty' => 'mudah'],
            ['word' => 'mewah', 'type' => 'sifat', 'difficulty' => 'mudah'],
            ['word' => 'sederhana', 'type' => 'sifat', 'difficulty' => 'mudah'],
            ['word' => 'mahal', 'type' => 'sifat', 'difficulty' => 'mudah'],
            ['word' => 'murah', 'type' => 'sifat', 'difficulty' => 'mudah'],
            ['word' => 'baru', 'type' => 'sifat', 'difficulty' => 'mudah'],
            ['word' => 'lama', 'type' => 'sifat', 'difficulty' => 'mudah'],
            ['word' => 'pintar', 'type' => 'sifat', 'difficulty' => 'mudah'],
            ['word' => 'bodoh', 'type' => 'sifat', 'difficulty' => 'mudah'],
            ['word' => 'kaya', 'type' => 'sifat', 'difficulty' => 'mudah'],
            ['word' => 'miskin', 'type' => 'sifat', 'difficulty' => 'mudah'],
            ['word' => 'indah', 'type' => 'sifat', 'difficulty' => 'mudah'],
            ['word' => 'rapi', 'type' => 'sifat', 'difficulty' => 'mudah'],
            ['word' => 'berani', 'type' => 'sifat', 'difficulty' => 'mudah'],
            ['word' => 'penakut', 'type' => 'sifat', 'difficulty' => 'mudah'],
            ['word' => 'jujur', 'type' => 'sifat', 'difficulty' => 'mudah'],
            ['word' => 'curang', 'type' => 'sifat', 'difficulty' => 'mudah'],
            ['word' => 'ramah', 'type' => 'sifat', 'difficulty' => 'mudah'],
            ['word' => 'pemarah', 'type' => 'sifat', 'difficulty' => 'mudah'],
            ['word' => 'sehat', 'type' => 'sifat', 'difficulty' => 'mudah'],
            ['word' => 'sakit', 'type' => 'sifat', 'difficulty' => 'mudah'],
            ['word' => 'wangi', 'type' => 'sifat', 'difficulty' => 'mudah'],
            ['word' => 'busuk', 'type' => 'sifat', 'difficulty' => 'mudah'],
            ['word' => 'halus', 'type' => 'sifat', 'difficulty' => 'mudah'],
        ]);
    }
}
